
export const ROUTE_LEND = 'ROUTE_LEND';
export const ROUTE_LIQUIDATED = 'ROUTE_LIQUIDATED';

export const ROUTE_ERRORS = 'ROUTE_ERRORS';
export const ROUTE_ERROR_404 = 'ROUTE_ERROR_404';

export const ROUTE_MARKETS = 'ROUTE_MARKETS';
export const ROUTE_MARKET_DETAILS = 'ROUTE_MARKET_DETAILS';

export const ROUTE_POOL = 'ROUTE_POOL';
export const ROUTE_POOL_POSITION = 'ROUTE_POOL_POSITION';
export const ROUTE_POOL_LIQUIDITY = 'ROUTE_POOL_LIQUIDITY';
export const ROUTE_POOL_LIQUIDITY_INCREASE = 'ROUTE_POOL_LIQUIDITY_INCREASE';
export const ROUTE_POOL_LIQUIDITY_REMOVE = 'ROUTE_POOL_LIQUIDITY_REMOVE';

export const ROUTE_STATIC_TERMS = 'ROUTE_STATIC_TERMS';
export const ROUTE_STATIC_LOANS = 'ROUTE_STATIC_LOANS';

export const ROUTE_DASHBOARD = 'ROUTE_DASHBOARD';
